### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by Purefreeman** [Spark-NF/twitter_media_downloader#10]
Would it be possible to separate how files are saved from all of it being in the same folder, into something like main folder twitter >> sub-folder posts(media the user posted) --- sub-folder retweets

**Comment by Spark-NF** [comment]
> main folder twitter >> sub-folder posts(media the user posted) --- sub-folder retweets

I'm not sure which structure you are trying to achieve.
Can you give me an example? Is it this?

```
some_user
├── retweets
│   ├── a.jpg
│   └── b.jpg
└── tweets
    ├── c.jpg
    └── d.jpg
```

**Comment by Purefreeman** [comment]
@Spark-NF yes 

Twitter
├── retweets
│   ├── a.jpg
│   └── b.jpg
└── tweets
    ├── c.jpg
    └── d.jpg

**Comment by Spark-NF** [comment]
Here you go 😄

You can now just add `%type%s/` add the beginning of your filename, and you'll get what you want. For example, `%type%s/[%date%] %filename%.%ext%`.
