### ISSUE TITLE
[Feature] import list of users. 

### ISSUE THREAD

**Issue by beakwood** [Spark-NF/twitter_media_downloader#14]
I have a list of users that I would like to download. Currently, I'm doing them manually one by one. Just wondering if the feature or is it possible to import a txt with a list of users. As I also notice that it updates the files that they are in without re-downloading them (I love this). Basically downloads the latest/current tweets.

**Comment by Spark-NF** [comment]
Hello 😄 

Sorry for the late answer I must have missed your email.
I just made a few changes to either pass multiple accounts to the CLI or pass a filename with the `@` prefix (`@file.txt`). I updated the README accordingly.
