### ISSUE TITLE
How can I make a list of users to download automatically

### ISSUE THREAD

**Issue by Alexo88** [Spark-NF/twitter_media_downloader#16]
I do not know how to make a list of users, I think the option is not enabled, I wonder if I can make a .bat ?.
What would you have to read to do it? I am interested in creating tools.

In other repositories focused on other pages they have an option to create a list of users, which simplifies my life, did anyone come up with a way to build a similar tool with this twitter repository?

**Comment by Alexo88** [comment]
ok i find it

**Admin:
I just made a few changes to either pass multiple accounts to the CLI or pass a filename with the @ prefix (@file.txt). I updated the README accordingly.**

**Comment by Spark-NF** [comment]
Yes, you can either just pass them all at the end of the command line (separated by spaces), or simply pass a file with the `@` prefix, one name per line. 👍
