### ISSUE TITLE
Install and download

### ISSUE THREAD

**Issue by jace344** [Spark-NF/twitter_media_downloader#26]
Hello
hello my brothers
I have little experience
Can you explain how to install l twitter-image-downloader

and how to download
Example: I want to download everything in the account
Thank you

**Comment by Spark-NF** [comment]
Hello

You can just download the repository on Github directly.
As to how to run it, there's an example in the README file:
```
python twitter_media_downloader.py -o out -f "[%date%] %filename%.%ext%" -s large -u Twitter
```

**Comment by jace344** [comment]
I have a problem
When I want to download
This error appears to me
What is the cause of the error
This is the python and pip version

Python 3.7.3

pip 21.2.4 from c:\users\pc\appdata\local\programs\python\python37-32\lib\site-p
ackages\pip (python 3.7)




Package                  Version
------------------------ -----------
aiodns                   3.0.0
aiohttp                  3.7.4.post0
aiohttp-socks            0.6.0
async-timeout            3.0.1
attrs                    21.2.0
beautifulsoup4           4.10.0
cchardet                 2.1.7
certifi                  2021.5.30
cffi                     1.14.6
chardet                  4.0.0
charset-normalizer       2.0.6
check-requirements-txt   1.0.2
colorama                 0.4.4
elasticsearch            7.15.0
fake-useragent           0.1.11
geographiclib            1.52
geopy                    2.2.0
googletransx             2.4.2
idna                     3.2
instaloader              4.8.1
multidict                5.2.0
numpy                    1.21.2
oauthlib                 3.1.1
pandas                   1.3.3
pip                      21.2.4
pycares                  4.0.0
pycparser                2.20
PySocks                  1.7.1
python-dateutil          2.8.2
python-socks             1.2.4
pytz                     2021.3
requests                 2.26.0
requests-oauthlib        1.3.0
schedule                 1.1.0
setuptools               58.2.0
six                      1.16.0
soupsieve                2.2.1
stdlib-list              0.8.0
tqdm                     4.62.3
tweepy                   4.1.0
twint                    2.1.20
twitter-media-downloader 1.0.0
typing-extensions        3.10.0.2
urllib3                  1.26.7
yarl                     1.7.0






C:\Users\pc>cd desktop

C:\Users\pc\Desktop>cd twitter_media_downloader-master

C:\Users\pc\Desktop\twitter_media_downloader-master>python twitter_media_downloa
der.py -o out -f "[%date%] %filename%.%ext%" -s large -u lpinderofficial
Traceback (most recent call last):
  File "twitter_media_downloader.py", line 38, in <module>
    medias = get_medias(AUTH, user_id, ARGS.retweets, ARGS.image_size, ARGS.sinc
e, ARGS.since_id, ARGS.until, ARGS.until_id, ARGS.likes)
  File "C:\Users\pc\Desktop\twitter_media_downloader-master\src\parser.py", line
 92, in get_medias
    api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=Tr
ue)
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_not
ify'

C:\Users\pc\Desktop\twitter_media_downloader-master>

**Comment by Bionus** [comment]
Hello

This is caused by a breaking change in [tweepy 4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0):
> * Remove API.wait_on_rate_limit_notify (f325738)
>   * Always log warning when rate limit reached

I updated the `requirements.txt` file to depend on 3.* instead.

**Comment by Spark-NF** [comment]
Hello

This is caused by a breaking change in [tweepy 4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0):
> * Remove API.wait_on_rate_limit_notify (f325738)
>   * Always log warning when rate limit reached

I updated the `requirements.txt` file to depend on 3.* instead.
