### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'

### ISSUE THREAD

**Issue by Jiroun** [Spark-NF/twitter_media_downloader#27]
at first try I got this error

TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'

how I can solve it 

`Traceback (most recent call last):
  File "twitter_media_downloader.py", line 38, in <module>
    medias = get_medias(AUTH, user_id, ARGS.retweets, ARGS.image_size, ARGS.since, ARGS.since_id, ARGS.until, ARGS.until_id, ARGS.likes)
  File "D:\twitter_media_downloader-master\src\parser.py", line 95, in get_medias
    api = tweepy.API(tweepy_auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'
`

**Comment by Bionus** [comment]
This is caused by a breaking change in [tweepy 4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0):
> * Remove API.wait_on_rate_limit_notify (f325738)
>   * Always log warning when rate limit reached

I updated the `requirements.txt` file to depend on 3.* instead.

**Comment by Hitomi98** [comment]
> This is caused by a breaking change in [tweepy 4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0):
> 
> > * Remove API.wait_on_rate_limit_notify (f325738)
> >   
> >   * Always log warning when rate limit reached
> 
> I updated the `requirements.txt` file to depend on 3.* instead.

Thanks! this worked I ran `pip3 install 'tweepy==3.7.0'` and it was able to run just fine after.
