### ISSUE TITLE
Acces token/Secret token

### ISSUE THREAD

**Issue by vincenzogianfelice** [Spark-NF/twitter_media_downloader#32]
what is **consumer key**/**secret** and **access token**/**secret**?

**Comment by francoarleite** [comment]
you need to create a developer account https://developer.twitter.com/ and create your own consumer key and access token

**Comment by Spark-NF** [comment]
Yes, as stated above those are your API OAuth "credentials" that you need to get one way or another.
Not sure how easy those are to obtain nowadays.
