### ISSUE TITLE
"No applicable tweets found" error

### ISSUE THREAD

**Issue by marvyn7** [Spark-NF/twitter_media_downloader#35]
![das](https://user-images.githubusercontent.com/87614316/197897306-c86735bf-2d89-42d9-a0eb-74cf1c64255f.png)
Basically, I was trying to download all the posts by a specific artist, however, he got over 3k posts on his media tab, including lots of memes and image reply, in any case, I tested 2 different applications for it.

Scrawler works, but, like the Dev himself told me, it is limited by Twitter's own structure, so it can only download the images from the last 1000 posts.

The other program I used was Twitter Media Downloader on Chrome, it worked kind well, despite some limitations in the ammount of images it can download. However, I noticed something.

It straight up refuses to download the posts from a specific time frame, November and December 2020, giving the message "No applicable tweets found" Other dates in the year can be downloaded without a problem, but not those 2 months. Is there any way to solve it, or recomment alternatives?

**Comment by Spark-NF** [comment]
Hello, are you mistaking this program for another one?

This is a python script that you have to run through `python twitter_media_downloader.py`, it has neither a GUI nor a Chrome extension. There's also no "No applicable tweets found" message in this program.

**Comment by marvyn7** [comment]
It was been almost a year, theres no need to reply this, I moved to another downloader long ago,
