### ISSUE TITLE
Only gets default (medium) image url, not large

### ISSUE THREAD

**Issue by sethcohn** [Spark-NF/twitter_media_downloader#4]
the API url defaults to medium, but can be larger, the url gets ":large" (or :small, etc) for other sizes

This should be a argument, I suspect.

**Comment by Spark-NF** [comment]
Yes indeed.

I just added a `-s` / `--image-size` argument to choose between the 4 possible values: `thumb`, `small`, `medium`, `large`. It defaults to `medium`.

If you choose `large` but the image does not have this size available for some reason, it will fallback to the default URL (without size indicator).
