### ISSUE TITLE
Dev? Where this script going?

### ISSUE THREAD

**Issue by EC-O-DE** [Spark-NF/twitter_media_downloader#6]
I wonder, because such as Tumblr and Reddit along FB and such has quite the a few tools - 3rd party - to DL content from those sites.

Python? Yes: Check **Downloader For Reddit** and **Reddit Data Extractor**. Other well done tool(s) is such as **TumblThree**.

Would be great to have something similar for Twitter - and so that it wouldn't be a browser addon.

**Comment by Spark-NF** [comment]
I'm not sure I understand your question/suggestion.

The program, for its intended original usage of downloading medias from given Twitter profiles, is pretty much done. What do you suggest exactly?

**Comment by EC-O-DE** [comment]
browser exts are nice but if the app is really want to expand - then it should run outside of browser.

**Comment by Spark-NF** [comment]
This is not a browser app though?
It's a standalone Python program.

**Comment by EC-O-DE** [comment]
Pardon. There's an ext at Chrome Web Store by the same name.
