### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Purefreeman** [Spark-NF/twitter_media_downloader#7]
Traceback (most recent call last):
  File "twitter_media_downloader.py", line 12, in <module>
    from parser import getMedias
ImportError: cannot import name 'getMedias'

**Comment by Spark-NF** [comment]
Could you provide more information about the context?

e.g.
* Your operating system
* The Python version you're using to run the program
* The command you used to run the program

So I can try to reproduce your issue :smile:

**Comment by Septan** [comment]
I having the same error.
I have windows 10 pro
Python 2.7.13
same command as your example, don't matter what user I put. I still get the same error.

**Comment by Spark-NF** [comment]
Indeed, it seems I wasn't myself using said command, using `./twitter_media_downloader.py` instead of `python twitter_media_downloader.py`. Should be solved now!
