### ISSUE TITLE
Set the start and end time?

### ISSUE THREAD

**Issue by zzzop** [Spark-NF/twitter_media_downloader#9]
Thanks for your work. The downloader is very useful. 
I just want to download the content of the last month. Is it possible?

**Comment by Spark-NF** [comment]
Hello

Currently, there is no such feature, the script will scrap everything the account posted without restraint.
I guess it could be considered as a feature improvement to add a few things:
* Maximum number of medias to download
* Download until ID
* Download until date

**Comment by Spark-NF** [comment]
Done!

You'll find the new options `--since`, `--since-id`, `--until`, and `--until-id` explained in [the README](https://github.com/Spark-NF/twitter_media_downloader#readme).

**Comment by zzzop** [comment]
So nice, thank you, Spark-NF. appreciate your taking the time.
